### ISSUE TITLE
[Question]: Tried adding a new parser for The Independent: Problems with Article Summary Selection

### ISSUE THREAD

**Issue by susannaruecker** [flairNLP/fundus#296]
### Question

Hey,

I'm testing Fundus right now. I followed the tutorials (really cool work! :+1: ) and now I'm trying to add a new Publisher and Parser, namely for the UK newspaper The Independent. (I don't have permission to push my branch, so I'm just pasting the code.)

For the most part, I was successfull (thanks for the step-by-step tutorial :rocket:): I managed to get the article attributes and the Sections, but I'm having some **issues when selecting the article summary** in for the body attribute.

I'm not too familiar with html and parsing with the CSSSelector, but I think the problem is the uncommon usage of a p element _inside_ the h2 element at most of the articles which seems to be a problem for my CSSSelector `CSSSelector("header[id='articleHeader'] h2 > p")`:

```html
<header id="articleHeader" class="sc-qvufca-5 hnKqFj">...
     <h1 class="sc-1xt8011-0 sc-qvufca-2 eLpUOs eBBoiW">Powerball: Can the winner of $1.02bn jackpot remain anonymous
     </h1>
     <h2 class="sc-aeekvc-0 eKSXmp">
          <p>The winning $1.02bn Powerball ticket was claimed in California </p>
     </h2>
</header>
```

I added a workaround which looks directly for p elements, and then chooses the right p on the condition of a h2 element directly before. This is of course not very elegant:

```python
class TheIndependentParser(ParserProxy):
    class V1(BaseParser):
        _paragraph_selector = CSSSelector("article div[id='main'] > p")
        _summary_selector = CSSSelector("header[id='articleHeader'] h2 > p")
        #_summary_selector = CSSSelector("header[id='articleHeader'] h2")

        @attribute
        def body(self) -> ArticleBody:
            body = extract_article_body_with_selector(
                self.precomputed.doc,
                summary_selector=self._summary_selector,
                paragraph_selector=self._paragraph_selector)
            if len(body.summary) == 0:
                article_header_paragraphs = CSSSelector("header[id='articleHeader'] p")(self.precomputed.doc)
                for p in article_header_paragraphs:
                    if p.getprevious().tag == "h2":
                        body.summary = TextSequence([p.text])
            return body

        @attribute
        def publishing_date(self) -> Optional[datetime.datetime]:
            return generic_date_parsing(self.precomputed.ld.bf_search("datePublished"))

        @attribute
        def authors(self) -> List[str]:
            return generic_author_parsing(self.precomputed.ld.bf_search("author"))

        @attribute
        def title(self) -> Optional[str]:
            return self.precomputed.ld.bf_search("headline")

        @attribute
        def topics(self) -> List[str]:
            return generic_topic_parsing(self.precomputed.meta.get("keywords"))

```

Furthermore, there also exist some articles in which the summary is **in fact** directly the h2 element, e.g.looking like:

```html
<h2 class="sc-aeekvc-0 eKSXmp">Lionesses captain Millie Bright will wear the ‘inclusion’, ‘Indigenous People’ 
    and ‘gender equality’ armbands during the group stage.
</h2>
```
But, when I tried using the Selector like so: `CSSSelector("header[id='articleHeader'] h2")`, then suddenly the whole article text got placed into the body.summary for whatever reason.

Any ideas how I can do it better and covering both (maybe there are more...) article cases? :slightly_smiling_face:

**Comment by MaxDall** [comment]
Hey @susannaruecker,
thanks for testing and adding a parser :) That really helps a lot. I also gave you `write` access to the repository so you can share your state of work.

Regarding your question:
Nice workaround btw. I had a similar problem once but didn't think about this solution 👍.
As you already pointed out the problem here is the usage of a paragraph tag inside a heading tag, which, according to [W3C](https://www.w3.org/TR/2012/WD-html-markup-20120329/h2.html) isn't allowed. It seems that the `lxml.html` parser is able to include the paragraph in the `_ElementTree` but not in the right position due to [`lxml.html.HTMLParser`](https://lxml.de/api/lxml.etree.HTMLParser-class.html)'s recover parameter.

``` python
import lxml.html

html = """
<html lang="de">
<h1>
    <p>paragraph within heading</p>
</h1>
<p>paragraph outside heading</p>
</html>
"""

root = lxml.html.document_fromstring(html)
print(lxml.html.tostring(root, pretty_print=True).decode())
```

prints

```console
<html lang="de">
<body>
<h1>
    </h1>
<p>paragraph within heading</p>

<p>paragraph outside heading</p>
</body>
</html>
```

I can't think of a way to separate these two cases using `XPath` or `CSSSelect`. As soon as `lxml` pushes the paragraph out of the heading it losses all its context information. So thinking about that I realized even the workaround wouldn't work reliably. IMO the right thing to do here would be to drop the summary.

I hope I could help you with this.

**Comment by susannaruecker** [comment]
Hey @MaxDall , thanks for the helpful comments and the write access! I will do so when I'm back from vacation, maybe with some more parsers. :)

Some (rather general) feedback for the tutorials/docs from my experience with them so far:

- minor but: sometimes the next says we’ll crawl 5 articles but the code only crawls two

- In Tutorial 2 about the `Article` class, maybe state more clearly your definitions  add of `title`, `summary`, `section`, `subheadline`and so on. Makes it easier to follow and to try out the different parts. Also: What is DOM?

- Tutorial 3 for filtering the articles, e. g. by author: As much as I like Donald Duck, maybe one could chose a different, more realistic, example so users actually get good results instead of waiting, maybe wondering if the system is still running or what 😅 Maybe filtering for a specific publishing time range, language or topic?

- Tutorial on How to add Parsers: This is already really cool and user-friendly! However, it could benefit from a bit more examples/details, especially regarding

1. More info or examples on how to find the specific URLs to Sitemap, NewsMap, RSSFeed, as well as what their differences and purposes are, and how/why the need to differentiate them. At least for me, this was new and I found myself a bit puzzled at first. 

2. Most importantly I would have liked more help for the basics of how to use the `CSSSelect` and `XPath` selectors, which is obviously the most work when adding a parser. I think that here, a small list of examples with html and some fitting example selectors, together with explanations what they do would be very helpful! Especially for keeping users interested that think about using your Iibrary (of course! 😉) but don’t have that much experience with html parsing yet. To keep the promise that it’s “easy to add a new parser”!

So far, hope this is somewhat helpful! :)

**Comment by MaxDall** [comment]
Thanks for the feedback 👍 @Weyaaron already opened issue #297 to address your comments.
