### ISSUE TITLE
[Bug]: WAZ not parsing properly

### ISSUE THREAD

**Issue by addie9800** [flairNLP/fundus#397]
### Describe the bug

This is an example article that does not get parsed (plaintext is None) https://www.waz.de/sport/lokalsport/bochum/article241975812/Tabubruch-Wattenscheid-Fans-schreiben-an-die-Stadt-Bochum.html 

### How to reproduce

```python
from fundus import Crawler, PublisherCollection

crawler = Crawler(PublisherCollection.de)

for article in crawler.crawl(max_articles=50, only_complete=False):
    print(article.title)
    print(article.free_access)
    print(article.html.responded_url)
    print(article.authors)
    print(article.topics)
    print(article.plaintext)
    print("\n")
```

### Expected behavior.

Parsed Plaintext

### Logs and Stack traces

```stacktrace
„Tabubruch“: Wattenscheid-Fans schreiben Offenen Brief an die Stadt Bochum
True
https://www.waz.de/sport/lokalsport/bochum/article241975812/Tabubruch-Wattenscheid-Fans-schreiben-an-die-Stadt-Bochum.html
['Philipp Ziser']
['Sporteinrichtung', 'Sportpolitik', 'Verein', 'Bochum', 'Milton Keynes', 'SG Wattenscheid 09', 'VfL Bochum', 'WAZ-Gruppe']
None
```

### Environment

```markdown
MACOS
```

**Comment by MaxDall** [comment]
Hey @addie9800 thanks for reporting this. 

It seems that there is already a PR #388 open, addressing some Issues regarding waz. Does this still happen using said branch?

**Comment by addie9800** [comment]
No, my bad. I came across this issue while working on another PR and didn't remember that you had already fixed it.
