### ISSUE TITLE
[Question]: News Publisher has two News site maps, what to do?

### ISSUE THREAD

**Issue by BorisKalika** [flairNLP/fundus#441]
### Question

Hello :) 

I want to add a new UK publisher to the list. When scouring for the news sitemap of the publisher through robots.txt, I discovered that it has 2 ("part1" && "part2") news sitemaps. 

What should I do in this case?

**Comment by MaxDall** [comment]
Hey @BorisKalika thank you for thinking about contributing :)

Could you provide me with the publisher's domain/name? Then I gonna give it a look and get back to you.

**Comment by BorisKalika** [comment]
Hello @MaxDall :)

It was BBC https://www.bbc.co.uk/ :)

Bots.txt gave me a Newsmap that was (for some reason) split into two parts.

**Comment by MaxDall** [comment]
Just to check if I understand you correctly: You're talking about https://www.bbc.co.uk/sitemaps/https-index-uk-news.xml ?

If so, the map you're referring to is an `indexmap`. There is also a part about those in the documentation.

Just add `NewsMap('https://www.bbc.co.uk/sitemaps/https-index-uk-news.xml')` as a source and Fundus will handle the rest. Per default, the package crawls through sitemaps recursively.

**Comment by BorisKalika** [comment]
Thank you! As I have already added The Sun, anyone is free to add BBC if they feel like it! (I don't want to hog newspapers)

If no one claims it till Thursday, I will add it myself.

Best regards :)!
