### ISSUE TITLE
Not able to use Fundus due to not being able to load  a library 

### ISSUE THREAD

**Issue by aaslan20** [flairNLP/fundus#449]
Problem: I can't use Fundus at all
Description: When trying to import something from Fundus I get the error that a library cannot be loaded
My attempt to solve it: I installed zlib 1.2.1, configured and compiled it in terminal. Lastly I added the path to my bash_profile so the libz.1.2.13.dylib can be loaded. Additionally I checked the rights for libz.1.2.13.dylib
Stack Trace: dlopen([/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/stream_io.cpython-39-darwin.so](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/stream_io.cpython-39-darwin.so), 2): Library not loaded: @loader_path[/.dylibs/libz.1.2.13.dylib](https://file+.vscode-resource.vscode-cdn.net/.dylibs/libz.1.2.13.dylib)
  Referenced from: [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/stream_io.cpython-39-darwin.so](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Environment:
OS: Mojave 10.14.6
Python: 3.9
Fundus: 0.3.0
Zlib: 1.2.13

**Comment by MaxDall** [comment]
@aaslan20 Sorry to hear that you're not able to run Fundus! 

Could you post the log/stack trace you are getting? Maybe check out this issue #284 for what I mean. The repository also supports issue templates for opening new issues to normalize things a bit.

**Comment by aaslan20** [comment]
Traceback (most recent call last):
  File "/Users/aliaslan/exercise-1-data-crawling-and-bow-classifier-aaslan20/task_1/fundus_crawler.py", line 2, in <module>
    from fundus import PublisherCollection, Crawler
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fundus/__init__.py", line 4, in <module>
    from fundus.scraping.crawler import CCNewsCrawler, Crawler, CrawlerBase
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fundus/scraping/crawler.py", line 40, in <module>
    from fundus.scraping.article import Article
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fundus/scraping/article.py", line 13, in <module>
    from fundus.scraping.html import HTML
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fundus/scraping/html.py", line 10, in <module>
    from fastwarc import ArchiveIterator, WarcRecord, WarcRecordType
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/__init__.py", line 15, in <module>
    from .stream_io import FileStream, GZipStream, LZ4Stream
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/stream_io.cpython-39-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libz.1.2.13.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/stream_io.cpython-39-darwin.so
  Reason: no suitable image found.  Did find:
        /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/.dylibs/libz.1.2.13.dylib: cannot load 'libz.1.2.13.dylib' (load command 0x80000034 is unknown)
        /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fastwarc/.dylibs/libz.1.2.13.dylib: cannot load 'libz.1.2.13.dylib' (load command 0x80000034 is unknown)

**Comment by MaxDall** [comment]
Thanks @aaslan20 :) Could you check if `pip install FastWARC==0.14.5` solves your issue for now?

**Comment by aaslan20** [comment]
I already have FastWARC==0.14.5 and I optionally tried to update it. The result is the same error, but instead of libz.1.2.13.dylib it wanted a newer version. For now I used Colab to solve my task with Fundus

**Comment by MaxDall** [comment]
@aaslan20 Maybe [this](https://github.com/mamba-org/mamba/issues/1826#issuecomment-1196636463) comment can solve your problem? Pls let me know if so :)
