### ISSUE TITLE
[Question]: Which ALPHA code should I use for the country India?

### ISSUE THREAD

**Issue by Senthi1Kumar** [flairNLP/fundus#528]
### Question

Hi there,

As I'm creating a new publisher for [The Hindu](https://www.thehindu.com/) from India and working on a Parser stub, I've encountered an issue with the alpha-2 code for India, which is `IN`. This code conflicts with the **_in_** keyword in Python, leading to a syntax error. Therefore, I propose using the alternate alpha-3 code `IND` to avoid this conflict. If we go with this naming convention, any other publishers for India will fall under `fundus/publishers/ind`.

Also, I've looked into the country codes with **_is_** keyword and found that the alpha-2 code for Iceland is `IS`, while the alpha-3 code is `ISL`. Therefore, any future publisher for Iceland would be located under `../../isl`.

**Comment by MaxDall** [comment]
@Senthi1Kumar That's a really good point and idea 👍 For now, I think the best would be to proceed as you suggested, using the alpha-3 code for India.

I will think about replacing the current alpha-2 code with alpha-2 ones, but this may take a while.

**Comment by Senthi1Kumar** [comment]
Thank you @MaxDall for the approval, I'll go with `ind` code and finish that first _publisher_ :).
